---
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          #cd $HOME
          rm -rf $HOME/rpmbuild
          yumdownloader --source kernel
          rpm -i *.rpm
          rm *.rpm
          cd $HOME/rpmbuild
          sed -i 's/^%define buildid \(.*\)$/%define buildid \1_erofs/' SPECS/kernel.spec
          rpmbuild -bp SPECS/kernel.spec
          sed -i 's/^# CONFIG_EROFS_FS is not set/CONFIG_EROFS_FS=m/' ./BUILD/kernel-*/linux-*.amzn2.x86_64/.config
          pushd kernel-*/linux-*/
          yes '' | make oldconfig
          popd
          # TODO: Modify the buildid
          rpmbuild -ba --without debug --without doc --without perf --without tools --without debuginfo --without kdump --without bootwrapper SPECS/kernel.spec
          rm -rf $HOME/rpmbuild
      - name: Upload generated RPMs
        uses: actions/upload-artifact@v3
        with:
          #name: RPMs
          path: /home/runner/rpmbuild/RPMS/x86_64/
